package communication;

import java.io.Serializable;

/** Represents an enumeration of messages that can be sent by the Server to Client.
 *
 */
public enum MessageFromServer implements Serializable {
    IMPORT_ORDERS_TABLE_NOT_SUCCEED,
    IMPORT_ORDERS_TABLE_SUCCEED,
    LOGIN_SUCCEED,
    LOGIN_NOT_SUCCEED,
    LOGOUT_SUCCEED,
    LOGOUT_NOT_SUCCEED,
    ALREADY_LOGGED_IN,
    SUCCESSFULLY_DISCONNECTED,
    CUSTOMER_IS_BLOCKED,
    IMPORTED_PRODUCTS_SUCCEED,
    SEND_ORDER_CATALOG,
    IMPORT_BRANCHES_NOT_SUCCEDD, 
    IMPORT_BRANCHES_SUCCEDD,
    ADDED_ORDER_SUCCESSFULLY,
    ADDED_ORDER_NOT_SUCCESSFULLY,
    ITEM_ADD_SUCCESS,
    ITEM_ADD_FAIL,
    ITEMS_GET_SUCCESS,
    ITEMS_GET_FAIL,
    ITEM_UPDATE_SUCCESS,
    ITEM_UPDATE_FAIL,
    ITEM_DELETE_SUCCESS,
    ITEM_DELETE_FAIL,
    PRODUCT_ADD_SUCCESS,
    PRODUCT_ADD_FAIL,
    PRODUCTS_GET_SUCCESS,
    PRODUCTS_GET_FAIL,
    PRODUCT_UPDATE_SUCCESS,
    PRODUCT_UPDATE_FAIL,
    PRODUCT_DELETE_SUCCESS,
    PRODUCT_DELETE_FAIL, PRODUCT_GET_ITEMS_FAIL, PRODUCT_GET_ITEMS_SUCCEED, ORDER_PRODUCTS_DELIVERED_SUCCESSFULLY, UPDATE_BALANCE_FAILED, UPDATE_BALANCE_SUCCEED, UPDATE_CARD_FAILED, UPDATE_CARD_SUCCEED,

}
